apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-dpl
  labels:
    app: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: myserver
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: server-svc
spec:
  selector:
    app: server
  ports:
   - port: 8000